# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'Friendship-UP' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Friendship-UP

pod 'VK-ios-sdk'
pod 'MBProgressHUD'
pod 'SVPullToRefresh'
pod 'SDWebImage'
pod 'Reachability'
pod 'AFNetworking', '~> 3.0'

end
